### ISSUE TITLE
Provide way to reset CommandScheduler

### ISSUE THREAD

**Issue by enjoydambience** [FTCLib/FTCLib#94]
**Is your feature request related to a problem? Please describe.**
There is no good way to reset `CommandScheduler`.

`CommandScheduler`, being a singleton, any configuration you add stays forever. This means:
- There is no easy way to reset at the end of every opmode
- There is no easy way to have different configurations for different opmodes
- No easy way to reset opmode when, e.g, hardwareMap changes
- It's very easy to accidentally have duplicate Subsystems/configurations
- `onXXX` additions are __permanent__

**Describe the solution you'd like**
Simplest way would be to provide a `reset()` mechanism.

However, I think that `CommandScheduler` should not have been a singleton in the first place, despite its convenience (a misuse of global state).
Changing this would be breaking, but it can be done well; If this option is taken I have some suggestions on how this could be done.

**Describe alternatives you've considered**
Calling `clearButtons(), cancelAll(), unregisterSubsystems(...)` etc. at the end of every opmode.
This doesn't clear everything though; subsystems have to be manually and externally tracked.

**Additional context**
Simply trying to create two different opmodes.

**Comment by JarnaChao09** [comment]
I'm just confused about what you mean needing to reset the `CommandScheduler` configurations. Could you give an example of a use case of your proposed changes? Why would there be a need for multiple instances of the `CommandScheduler`? Since `CommandScheduler` access hardware, all hardware is synchronized, so multiple instances calling different commands for the same subsystem wouldn't work since they are interruptible and one would override the other.

**Comment by dansman805** [comment]
`CommandScheduler` should be a normal class; the reason WPILib `CommandScheduler` can be a singleton without issue is there is a single `Robot` class and no seperate OpModes. With a normal class, you could construct a new one each OpMode, so you don't have issues with state carrying over.

**Comment by JIceberg** [comment]
Good points @dansman805 @enjoydambience. Do you guys have any suggestions as to how this could be done effectively?

**Comment by JIceberg** [comment]
Looks like this can be done with something as simple as removing the instance method and making the constructor public.

**Comment by JIceberg** [comment]
@enjoydambience Do you have any suggestions as to how the rest of the paradigm can be modeled around this change?

**Comment by enjoydambience** [comment]
Use cases for different CommandScheduler config:
- If hardware config changes, hardwareMap is updated; subsystems will need to be reconstructed, as will commands that reference subsystems
- onCommandStart etc. could be useful for debugging but is not needed all the time; would want ability to configure
- You probably want to cancel all commands on opMode stop
- There is no one configuration entrypoint in FTC sdk


Turning a singleton into a not-singleton could take a lot of work; and also, as @JarnaChao09 mentioned, there is no need for more than one CommandScheduler, just more than one config. So it might be better to make CommandScheduler a "resetable" singleton, but this feels like a weird pattern.
This could work:
```java
public synchronized void reset() { instance = null; }
```

**Comment by JIceberg** [comment]
> If hardware config changes, hardwareMap is updated; subsystems will need to be reconstructed, as will commands that reference subsystems

I'm not sure about the number of people who are doing this. In my opinion, changing hardware configs between opmodes is definitely a user-side issue of efficiency.

> You probably want to cancel all commands on opMode stop

I think this can be done effectively by clearing the scheduler at the end of the opmode.

The suggestion you provided looks like it would work due to the way the `getInstance()` method is laid out. It's kinda clumsy, but I think it fits the desired result.

**Comment by JIceberg** [comment]
Implementation added for v1.1.0. Thanks for the suggestion!
